# See https://redocly.com/docs/cli/configuration/ for more information.
apis:
  sample@v1:
    root: src/synklink-openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: error
features.openapi:
  showConsole: true
  htmlTemplate: src/docs/index.html

  theme:
    colors:
      primary:
        main: "#32329f"
